# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

p = int(input("How many terms of the fibonacci series do you want to print?:"))
def fibo(n):
  if(n==0 or n==1):
    return n
  else:
    return fibo(n-2) + fibo(n-1)
n = 0
while n < p:
 print(fibo(n))
 n = n + 1